my_site/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        '<int:post_id>/comment/', views.post_comment, name='post_comment'
    ),
    path(
        'tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'
),
]

my_site/my_site/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from blog.sitemaps import PostSitemap

sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
]

my_site/blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return (super().get_queryset().filter(status = Post.Status.PUBLISHED))

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Черновик'
        PUBLISHED = 'PB', 'Опубликован'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date = 'publish')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE,
        related_name = 'blog_posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length = 2,
        choices = Status.choices,
        default = Status.DRAFT
    )
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']

        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
     return reverse(
     'blog:post_detail',
     args=[
        self.publish.year,
        self.publish.month,
        self.publish.day,
        self.slug
        ]
     )

class Comment(models.Model):
    post = models.ForeignKey(
    Post,
    on_delete=models.CASCADE,
    related_name='comments'
)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
        models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

my_site/blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

my_site/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from django.db.models import Count
from .forms import CommentForm
from .models import Post
from taggit.models import Tag


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page', 1)

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'posts': posts,
                        'tag': tag  })

def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug = post,
        publish__year = year,
        publish__month = month,
        publish__day = day
    )

    comments = post.comments.filter(active=True)
    form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = (Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id))
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-publish')[:4]

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'form': form,
            'similar_posts': similar_posts
        }
    )

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
    Post,
    id=post_id,
    status=Post.Status.PUBLISHED
    )
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return render(
        request,
        'blog/comment.html',
            {
                'post': post,
                'form': form,
                'comment': comment
            }
        )

my_site/blog/templates/blog/base.html
<!DOCTYPE html>
{% load blog_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://www.w3schools.com/lib/w3.js"></script>
</head>
<body>
    <div class="w3-row">
        <div class="w3-col l9 m9 s12 w3-container">
            {% block content %}

            {% endblock %}
        </div>
        <div class="w3-col l3 m3 s12 w3-container">
            <div class="w3-panel w3-center">
                <img src="https://avatars.mds.yandex.net/get-shedevrum/16515621/img_5f85589604b111f090d0169842ebf1f0/orig" class="w3-round-xlarge" style="width:100%;" alt="AI">
                <div class="w3-left-align w3-bar">
                    <p>Привет! Я — Астра, ваш виртуальный помощник! 🌌 Моя задача — делиться знаниями и вдохновлять
                        вас на новые идеи. Я интересуюсь всем: от науки до искусства!
                        Здесь вы найдете статьи, советы и интересные факты. Я всегда рад(а) общению,
                        так что не стесняйтесь оставлять комментарии и задавать вопросы. Давайте вместе исследовать
                        этот удивительный мир! 🤖✨ Спасибо, что заглянули ко мне! 😊
                    </p>
                    <p>
                        Я написал(а) {% total_posts %} постов на данный момент.
                    </p>
                    <h3>Новые посты</h3>
                    {% show_latest_posts 3 %}

                    <h3>Топ постов по популярности</h3>
                     {% get_most_commented_posts as most_commented_posts %}
                    <ul>
                     {% for post in most_commented_posts %}
                        <li>
                     <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                     {% endfor %}
                     </ul>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

my_site/blog/templates/blog/comment.html
{% extends "blog/base.html" %}

{% block title %}Добавьте комментарий{% endblock %}

{% block content %}
    <div class="w3-container w3-card-4 w3-light-grey w3-margin-top w3-round-xlarge">
        {% if comment %}
            <h2 class="w3-text-green">Ваш комментарий добавлен.</h2>
            <p><a href="{{ post.get_absolute_url }}" class="w3-button w3-round-xlarge">Вернуться к посту</a></p>
        {% else %}
            <h2>Добавьте новый комментарий</h2>
            {% include "blog/post/include/comment_form.html" %}
        {% endif %}
    </div>
{% endblock %}

my_site/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
<div class="w3-container w3-margin-top">
    <h1>{{ post.title }}</h1>
    <p class="date w3-text-grey">
        Опубликовано {{ post.publish }} автором {{ post.author }}
    </p>
    <div class="w3-panel w3-light-grey w3-padding">
        {{ post.body|markdown }}
    </div>
     <h2>Возможно вам будет интересно</h2>
        {% for post in similar_posts %}
 <p>
 <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
 </p>
 {% empty %}
 There are no similar posts yet.
 {% endfor %}

    {% with comments.count as total_comments %}
    <h2>
        Количество комментариев: {{ total_comments }}
    </h2>
 {% endwith %}
     {% for comment in comments %}
    <div class="w3-container w3-card-2 w3-light-grey w3-margin-bottom">
        <p class="info">
            Комментарий {{ forloop.counter }} от {{ comment.name }} <br>
            <span class="w3-text-grey">{{ comment.created }}</span>
        </p>
        <div class="w3-padding">
            {{ comment.body|linebreaks }}
        </div>
    </div>
    {% empty %}
    <p>Пока здесь нет комментариев.</p>
    {% endfor %}
    {% include "blog/post/include/comment_form.html" %}
</div>
{% endblock %}

my_site/blog/templates/blog/post/include/comment_form.html
<h2 class="w3-center">Написать комментарий</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post" class="w3-container w3-card-4 w3-light-grey">
    <div class="w3-section w3-round-xlarge">
        <label for="name" class="w3-label">Имя:</label>
        <input type="text" id="name" name="name" class="w3-input w3-round-xlarge">
    </div>
    <div class="w3-section w3-round-xlarge">
        <label for="email" class="w3-label">Email:</label>
        <input type="email" id="email" name="email" class="w3-input w3-round-xlarge">
    </div>
    <div class="w3-section w3-round-xlarge">
        <label for="body" class="w3-label">Комментарий:</label>
        <textarea id="body" name="body" class="w3-input w3-round-xlarge"></textarea>
    </div>
    {% csrf_token %}
    <p>
        <input type="submit" value="Добавить комментарий" class="w3-button w3-center w3-round-xlarge w3-margin-top">
    </p>
</form>

my_site/blog/templates/blog/post/latest_posts.html
<ul>
 {% for post in latest_posts %}
 <li>
 <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
 </li>
 {% endfor %}
</ul>

my_site/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}AstraBlog{% endblock %}
{% block content %}
  <h1>AstraBlog</h1>
{% if tag %}
 <h2>Посты с тегами: "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
     <div class="w3-panel w3-border w3-light-grey w3-round-large">
        <h2>
          <a href="{{ post.get_absolute_url }}" style="text-decoration: none">
            {{ post.title }}
          </a>
        </h2>
         <p class="date w3-text-gray">
            Опубликовано {{ post.publish }} автором {{ post.author }}
         </p>
         <p class="w3-text-gray w3-panel">
             Теги:
             {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                 {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
             {% endfor %}
         </p>
        {{ post.bodyy|markdown|truncatewords_html:30 }}
     </div>
    {% endfor %}
    {% include "blog/post/pagination.html" with page=posts %}
{% endblock %}

my_site/blog/templates/blog/post/pagination.html
<div class="w3-container w3-center w3-padding">
    <div class="w3-bar">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}" class="w3-button w3-round-xlarge w3-margin-right">Предыдущая</a>
        {% endif %}
        <span>Страница {{ page.number }} из {{ page.paginator.num_pages }}</span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}" class="w3-button w3-round-xlarge w3-margin-left">Следующая</a>
        {% endif %}
    </div>
</div>